# Generated by Django 4.2.7 on 2023-11-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
